Import library yang diperlukkan.

In [1]:
import numpy as np
import pandas as pd
from keras.layers import Dense
from keras.models import Sequential
import tensorflow as tf

Memuat data csv

In [2]:
dataset = pd.read_csv('Datatest.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[2.555875e+08 1.380000e+00]
 [2.584965e+08 1.360000e+00]
 [2.613555e+08 1.340000e+00]
 [2.641616e+08 1.330000e+00]
 [2.669119e+08 1.310000e+00]
 [2.702039e+08 1.250000e+00]
 [2.726825e+08 1.220000e+00]]


In [4]:
print(y)

[105303318 112205711 118922708 126508776 133617012 136137451 141992573]


Membagi data menjadi data latih dan data uji

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

[[2.584965e+08 1.360000e+00]
 [2.641616e+08 1.330000e+00]
 [2.555875e+08 1.380000e+00]
 [2.702039e+08 1.250000e+00]
 [2.669119e+08 1.310000e+00]]


In [7]:
print(y_train)

[112205711 126508776 105303318 136137451 133617012]


In [8]:
print(X_test)

[[2.726825e+08 1.220000e+00]
 [2.613555e+08 1.340000e+00]]


In [9]:
print(y_test)

[141992573 118922708]


Normalisasi/FeatureScaling data menggunakan StandardScaler

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1, 1))
y_test = sc_y.transform(y_test.reshape(-1, 1))

In [11]:
print(X_train)

[[-0.85339034  0.75574218]
 [ 0.20315994  0.08891084]
 [-1.39592353  1.20029641]
 [ 1.33005862 -1.68930605]
 [ 0.71609532 -0.35564338]]


In [12]:
print(X_test)

[[ 1.79232152 -2.35613739]
 [-0.32018224  0.31118796]]


Membuat model Artificial Neural Network

In [13]:
model = Sequential()
model.add(Dense(units=5, activation='relu'))
model.add(Dense(units=5,activation='relu'))
model.add(Dense(units=5,activation='relu'))
model.add(Dense(units=1 ,activation='sigmoid'))

In [14]:
model.compile(loss='mean_absolute_error', optimizer='adam')


Melatih ANN

In [15]:
model.fit(X_train, y_train, epochs=2000,  validation_data=(X_test, y_test), verbose=2)


Epoch 1/2000
1/1 - 1s - loss: 0.8838 - val_loss: 0.8895 - 539ms/epoch - 539ms/step
Epoch 2/2000
1/1 - 0s - loss: 0.8830 - val_loss: 0.8880 - 16ms/epoch - 16ms/step
Epoch 3/2000
1/1 - 0s - loss: 0.8823 - val_loss: 0.8866 - 17ms/epoch - 17ms/step
Epoch 4/2000
1/1 - 0s - loss: 0.8815 - val_loss: 0.8851 - 15ms/epoch - 15ms/step
Epoch 5/2000
1/1 - 0s - loss: 0.8807 - val_loss: 0.8835 - 16ms/epoch - 16ms/step
Epoch 6/2000
1/1 - 0s - loss: 0.8799 - val_loss: 0.8820 - 16ms/epoch - 16ms/step
Epoch 7/2000
1/1 - 0s - loss: 0.8791 - val_loss: 0.8804 - 15ms/epoch - 15ms/step
Epoch 8/2000
1/1 - 0s - loss: 0.8783 - val_loss: 0.8789 - 16ms/epoch - 16ms/step
Epoch 9/2000
1/1 - 0s - loss: 0.8775 - val_loss: 0.8773 - 16ms/epoch - 16ms/step
Epoch 10/2000
1/1 - 0s - loss: 0.8767 - val_loss: 0.8757 - 15ms/epoch - 15ms/step
Epoch 11/2000
1/1 - 0s - loss: 0.8759 - val_loss: 0.8743 - 16ms/epoch - 16ms/step
Epoch 12/2000
1/1 - 0s - loss: 0.8750 - val_loss: 0.8730 - 15ms/epoch - 15ms/step
Epoch 13/2000
1/1 - 0s 

Epoch 101/2000
1/1 - 0s - loss: 0.7909 - val_loss: 0.7320 - 16ms/epoch - 16ms/step
Epoch 102/2000
1/1 - 0s - loss: 0.7899 - val_loss: 0.7308 - 16ms/epoch - 16ms/step
Epoch 103/2000
1/1 - 0s - loss: 0.7890 - val_loss: 0.7297 - 16ms/epoch - 16ms/step
Epoch 104/2000
1/1 - 0s - loss: 0.7880 - val_loss: 0.7286 - 15ms/epoch - 15ms/step
Epoch 105/2000
1/1 - 0s - loss: 0.7870 - val_loss: 0.7275 - 16ms/epoch - 16ms/step
Epoch 106/2000
1/1 - 0s - loss: 0.7861 - val_loss: 0.7264 - 15ms/epoch - 15ms/step
Epoch 107/2000
1/1 - 0s - loss: 0.7852 - val_loss: 0.7253 - 16ms/epoch - 16ms/step
Epoch 108/2000
1/1 - 0s - loss: 0.7842 - val_loss: 0.7242 - 15ms/epoch - 15ms/step
Epoch 109/2000
1/1 - 0s - loss: 0.7833 - val_loss: 0.7231 - 14ms/epoch - 14ms/step
Epoch 110/2000
1/1 - 0s - loss: 0.7824 - val_loss: 0.7221 - 15ms/epoch - 15ms/step
Epoch 111/2000
1/1 - 0s - loss: 0.7815 - val_loss: 0.7211 - 15ms/epoch - 15ms/step
Epoch 112/2000
1/1 - 0s - loss: 0.7806 - val_loss: 0.7202 - 16ms/epoch - 16ms/step
Epoc

Epoch 200/2000
1/1 - 0s - loss: 0.7245 - val_loss: 0.6789 - 16ms/epoch - 16ms/step
Epoch 201/2000
1/1 - 0s - loss: 0.7239 - val_loss: 0.6787 - 15ms/epoch - 15ms/step
Epoch 202/2000
1/1 - 0s - loss: 0.7233 - val_loss: 0.6785 - 16ms/epoch - 16ms/step
Epoch 203/2000
1/1 - 0s - loss: 0.7227 - val_loss: 0.6783 - 18ms/epoch - 18ms/step
Epoch 204/2000
1/1 - 0s - loss: 0.7221 - val_loss: 0.6781 - 16ms/epoch - 16ms/step
Epoch 205/2000
1/1 - 0s - loss: 0.7215 - val_loss: 0.6779 - 16ms/epoch - 16ms/step
Epoch 206/2000
1/1 - 0s - loss: 0.7210 - val_loss: 0.6777 - 17ms/epoch - 17ms/step
Epoch 207/2000
1/1 - 0s - loss: 0.7205 - val_loss: 0.6774 - 16ms/epoch - 16ms/step
Epoch 208/2000
1/1 - 0s - loss: 0.7199 - val_loss: 0.6772 - 15ms/epoch - 15ms/step
Epoch 209/2000
1/1 - 0s - loss: 0.7194 - val_loss: 0.6770 - 15ms/epoch - 15ms/step
Epoch 210/2000
1/1 - 0s - loss: 0.7188 - val_loss: 0.6768 - 16ms/epoch - 16ms/step
Epoch 211/2000
1/1 - 0s - loss: 0.7183 - val_loss: 0.6766 - 16ms/epoch - 16ms/step
Epoc

Epoch 299/2000
1/1 - 0s - loss: 0.6152 - val_loss: 0.6249 - 16ms/epoch - 16ms/step
Epoch 300/2000
1/1 - 0s - loss: 0.6139 - val_loss: 0.6242 - 16ms/epoch - 16ms/step
Epoch 301/2000
1/1 - 0s - loss: 0.6126 - val_loss: 0.6234 - 15ms/epoch - 15ms/step
Epoch 302/2000
1/1 - 0s - loss: 0.6119 - val_loss: 0.6227 - 16ms/epoch - 16ms/step
Epoch 303/2000
1/1 - 0s - loss: 0.6115 - val_loss: 0.6220 - 16ms/epoch - 16ms/step
Epoch 304/2000
1/1 - 0s - loss: 0.6112 - val_loss: 0.6213 - 15ms/epoch - 15ms/step
Epoch 305/2000
1/1 - 0s - loss: 0.6108 - val_loss: 0.6207 - 16ms/epoch - 16ms/step
Epoch 306/2000
1/1 - 0s - loss: 0.6104 - val_loss: 0.6201 - 15ms/epoch - 15ms/step
Epoch 307/2000
1/1 - 0s - loss: 0.6100 - val_loss: 0.6195 - 16ms/epoch - 16ms/step
Epoch 308/2000
1/1 - 0s - loss: 0.6095 - val_loss: 0.6190 - 15ms/epoch - 15ms/step
Epoch 309/2000
1/1 - 0s - loss: 0.6090 - val_loss: 0.6184 - 15ms/epoch - 15ms/step
Epoch 310/2000
1/1 - 0s - loss: 0.6085 - val_loss: 0.6179 - 16ms/epoch - 16ms/step
Epoc

Epoch 398/2000
1/1 - 0s - loss: 0.5473 - val_loss: 0.5710 - 15ms/epoch - 15ms/step
Epoch 399/2000
1/1 - 0s - loss: 0.5466 - val_loss: 0.5703 - 16ms/epoch - 16ms/step
Epoch 400/2000
1/1 - 0s - loss: 0.5458 - val_loss: 0.5696 - 16ms/epoch - 16ms/step
Epoch 401/2000
1/1 - 0s - loss: 0.5450 - val_loss: 0.5689 - 16ms/epoch - 16ms/step
Epoch 402/2000
1/1 - 0s - loss: 0.5441 - val_loss: 0.5683 - 16ms/epoch - 16ms/step
Epoch 403/2000
1/1 - 0s - loss: 0.5432 - val_loss: 0.5677 - 16ms/epoch - 16ms/step
Epoch 404/2000
1/1 - 0s - loss: 0.5428 - val_loss: 0.5670 - 15ms/epoch - 15ms/step
Epoch 405/2000
1/1 - 0s - loss: 0.5422 - val_loss: 0.5665 - 16ms/epoch - 16ms/step
Epoch 406/2000
1/1 - 0s - loss: 0.5414 - val_loss: 0.5659 - 16ms/epoch - 16ms/step
Epoch 407/2000
1/1 - 0s - loss: 0.5406 - val_loss: 0.5652 - 16ms/epoch - 16ms/step
Epoch 408/2000
1/1 - 0s - loss: 0.5397 - val_loss: 0.5644 - 15ms/epoch - 15ms/step
Epoch 409/2000
1/1 - 0s - loss: 0.5389 - val_loss: 0.5637 - 16ms/epoch - 16ms/step
Epoc

Epoch 497/2000
1/1 - 0s - loss: 0.5026 - val_loss: 0.5204 - 16ms/epoch - 16ms/step
Epoch 498/2000
1/1 - 0s - loss: 0.5024 - val_loss: 0.5201 - 16ms/epoch - 16ms/step
Epoch 499/2000
1/1 - 0s - loss: 0.5022 - val_loss: 0.5198 - 16ms/epoch - 16ms/step
Epoch 500/2000
1/1 - 0s - loss: 0.5021 - val_loss: 0.5195 - 16ms/epoch - 16ms/step
Epoch 501/2000
1/1 - 0s - loss: 0.5018 - val_loss: 0.5194 - 16ms/epoch - 16ms/step
Epoch 502/2000
1/1 - 0s - loss: 0.5018 - val_loss: 0.5191 - 16ms/epoch - 16ms/step
Epoch 503/2000
1/1 - 0s - loss: 0.5016 - val_loss: 0.5187 - 15ms/epoch - 15ms/step
Epoch 504/2000
1/1 - 0s - loss: 0.5015 - val_loss: 0.5184 - 15ms/epoch - 15ms/step
Epoch 505/2000
1/1 - 0s - loss: 0.5013 - val_loss: 0.5181 - 16ms/epoch - 16ms/step
Epoch 506/2000
1/1 - 0s - loss: 0.5011 - val_loss: 0.5177 - 15ms/epoch - 15ms/step
Epoch 507/2000
1/1 - 0s - loss: 0.5010 - val_loss: 0.5174 - 16ms/epoch - 16ms/step
Epoch 508/2000
1/1 - 0s - loss: 0.5008 - val_loss: 0.5172 - 16ms/epoch - 16ms/step
Epoc

Epoch 596/2000
1/1 - 0s - loss: 0.4932 - val_loss: 0.4995 - 15ms/epoch - 15ms/step
Epoch 597/2000
1/1 - 0s - loss: 0.4930 - val_loss: 0.4993 - 15ms/epoch - 15ms/step
Epoch 598/2000
1/1 - 0s - loss: 0.4930 - val_loss: 0.4992 - 16ms/epoch - 16ms/step
Epoch 599/2000
1/1 - 0s - loss: 0.4929 - val_loss: 0.4991 - 16ms/epoch - 16ms/step
Epoch 600/2000
1/1 - 0s - loss: 0.4929 - val_loss: 0.4990 - 15ms/epoch - 15ms/step
Epoch 601/2000
1/1 - 0s - loss: 0.4928 - val_loss: 0.4988 - 15ms/epoch - 15ms/step
Epoch 602/2000
1/1 - 0s - loss: 0.4929 - val_loss: 0.4987 - 15ms/epoch - 15ms/step
Epoch 603/2000
1/1 - 0s - loss: 0.4927 - val_loss: 0.4986 - 15ms/epoch - 15ms/step
Epoch 604/2000
1/1 - 0s - loss: 0.4930 - val_loss: 0.4984 - 17ms/epoch - 17ms/step
Epoch 605/2000
1/1 - 0s - loss: 0.4930 - val_loss: 0.4982 - 17ms/epoch - 17ms/step
Epoch 606/2000
1/1 - 0s - loss: 0.4927 - val_loss: 0.4980 - 16ms/epoch - 16ms/step
Epoch 607/2000
1/1 - 0s - loss: 0.4928 - val_loss: 0.4978 - 17ms/epoch - 17ms/step
Epoc

Epoch 695/2000
1/1 - 0s - loss: 0.4909 - val_loss: 0.4889 - 16ms/epoch - 16ms/step
Epoch 696/2000
1/1 - 0s - loss: 0.4909 - val_loss: 0.4888 - 16ms/epoch - 16ms/step
Epoch 697/2000
1/1 - 0s - loss: 0.4907 - val_loss: 0.4889 - 16ms/epoch - 16ms/step
Epoch 698/2000
1/1 - 0s - loss: 0.4902 - val_loss: 0.4889 - 16ms/epoch - 16ms/step
Epoch 699/2000
1/1 - 0s - loss: 0.4903 - val_loss: 0.4889 - 17ms/epoch - 17ms/step
Epoch 700/2000
1/1 - 0s - loss: 0.4905 - val_loss: 0.4888 - 16ms/epoch - 16ms/step
Epoch 701/2000
1/1 - 0s - loss: 0.4903 - val_loss: 0.4887 - 16ms/epoch - 16ms/step
Epoch 702/2000
1/1 - 0s - loss: 0.4902 - val_loss: 0.4886 - 16ms/epoch - 16ms/step
Epoch 703/2000
1/1 - 0s - loss: 0.4905 - val_loss: 0.4885 - 15ms/epoch - 15ms/step
Epoch 704/2000
1/1 - 0s - loss: 0.4906 - val_loss: 0.4884 - 15ms/epoch - 15ms/step
Epoch 705/2000
1/1 - 0s - loss: 0.4903 - val_loss: 0.4884 - 17ms/epoch - 17ms/step
Epoch 706/2000
1/1 - 0s - loss: 0.4900 - val_loss: 0.4884 - 17ms/epoch - 17ms/step
Epoc

Epoch 794/2000
1/1 - 0s - loss: 0.4892 - val_loss: 0.4833 - 16ms/epoch - 16ms/step
Epoch 795/2000
1/1 - 0s - loss: 0.4891 - val_loss: 0.4833 - 17ms/epoch - 17ms/step
Epoch 796/2000
1/1 - 0s - loss: 0.4893 - val_loss: 0.4832 - 16ms/epoch - 16ms/step
Epoch 797/2000
1/1 - 0s - loss: 0.4893 - val_loss: 0.4831 - 15ms/epoch - 15ms/step
Epoch 798/2000
1/1 - 0s - loss: 0.4890 - val_loss: 0.4830 - 16ms/epoch - 16ms/step
Epoch 799/2000
1/1 - 0s - loss: 0.4891 - val_loss: 0.4829 - 15ms/epoch - 15ms/step
Epoch 800/2000
1/1 - 0s - loss: 0.4893 - val_loss: 0.4828 - 16ms/epoch - 16ms/step
Epoch 801/2000
1/1 - 0s - loss: 0.4892 - val_loss: 0.4828 - 16ms/epoch - 16ms/step
Epoch 802/2000
1/1 - 0s - loss: 0.4891 - val_loss: 0.4829 - 15ms/epoch - 15ms/step
Epoch 803/2000
1/1 - 0s - loss: 0.4891 - val_loss: 0.4828 - 15ms/epoch - 15ms/step
Epoch 804/2000
1/1 - 0s - loss: 0.4891 - val_loss: 0.4828 - 16ms/epoch - 16ms/step
Epoch 805/2000
1/1 - 0s - loss: 0.4890 - val_loss: 0.4827 - 16ms/epoch - 16ms/step
Epoc

Epoch 893/2000
1/1 - 0s - loss: 0.4883 - val_loss: 0.4794 - 15ms/epoch - 15ms/step
Epoch 894/2000
1/1 - 0s - loss: 0.4885 - val_loss: 0.4794 - 15ms/epoch - 15ms/step
Epoch 895/2000
1/1 - 0s - loss: 0.4886 - val_loss: 0.4794 - 17ms/epoch - 17ms/step
Epoch 896/2000
1/1 - 0s - loss: 0.4884 - val_loss: 0.4794 - 16ms/epoch - 16ms/step
Epoch 897/2000
1/1 - 0s - loss: 0.4884 - val_loss: 0.4794 - 15ms/epoch - 15ms/step
Epoch 898/2000
1/1 - 0s - loss: 0.4887 - val_loss: 0.4794 - 16ms/epoch - 16ms/step
Epoch 899/2000
1/1 - 0s - loss: 0.4887 - val_loss: 0.4793 - 15ms/epoch - 15ms/step
Epoch 900/2000
1/1 - 0s - loss: 0.4885 - val_loss: 0.4792 - 15ms/epoch - 15ms/step
Epoch 901/2000
1/1 - 0s - loss: 0.4883 - val_loss: 0.4791 - 16ms/epoch - 16ms/step
Epoch 902/2000
1/1 - 0s - loss: 0.4885 - val_loss: 0.4791 - 16ms/epoch - 16ms/step
Epoch 903/2000
1/1 - 0s - loss: 0.4883 - val_loss: 0.4791 - 16ms/epoch - 16ms/step
Epoch 904/2000
1/1 - 0s - loss: 0.4883 - val_loss: 0.4791 - 17ms/epoch - 17ms/step
Epoc

Epoch 992/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4767 - 16ms/epoch - 16ms/step
Epoch 993/2000
1/1 - 0s - loss: 0.4879 - val_loss: 0.4767 - 17ms/epoch - 17ms/step
Epoch 994/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4767 - 15ms/epoch - 15ms/step
Epoch 995/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4767 - 16ms/epoch - 16ms/step
Epoch 996/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4766 - 15ms/epoch - 15ms/step
Epoch 997/2000
1/1 - 0s - loss: 0.4879 - val_loss: 0.4766 - 17ms/epoch - 17ms/step
Epoch 998/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4765 - 15ms/epoch - 15ms/step
Epoch 999/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4765 - 17ms/epoch - 17ms/step
Epoch 1000/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4765 - 16ms/epoch - 16ms/step
Epoch 1001/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4765 - 16ms/epoch - 16ms/step
Epoch 1002/2000
1/1 - 0s - loss: 0.4879 - val_loss: 0.4765 - 15ms/epoch - 15ms/step
Epoch 1003/2000
1/1 - 0s - loss: 0.4878 - val_loss: 0.4765 - 15ms/epoch - 15ms/step


Epoch 1090/2000
1/1 - 0s - loss: 0.4877 - val_loss: 0.4747 - 16ms/epoch - 16ms/step
Epoch 1091/2000
1/1 - 0s - loss: 0.4879 - val_loss: 0.4748 - 16ms/epoch - 16ms/step
Epoch 1092/2000
1/1 - 0s - loss: 0.4879 - val_loss: 0.4747 - 15ms/epoch - 15ms/step
Epoch 1093/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4747 - 16ms/epoch - 16ms/step
Epoch 1094/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4746 - 16ms/epoch - 16ms/step
Epoch 1095/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4746 - 16ms/epoch - 16ms/step
Epoch 1096/2000
1/1 - 0s - loss: 0.4879 - val_loss: 0.4746 - 16ms/epoch - 16ms/step
Epoch 1097/2000
1/1 - 0s - loss: 0.4878 - val_loss: 0.4746 - 16ms/epoch - 16ms/step
Epoch 1098/2000
1/1 - 0s - loss: 0.4877 - val_loss: 0.4745 - 15ms/epoch - 15ms/step
Epoch 1099/2000
1/1 - 0s - loss: 0.4876 - val_loss: 0.4745 - 16ms/epoch - 16ms/step
Epoch 1100/2000
1/1 - 0s - loss: 0.4877 - val_loss: 0.4744 - 15ms/epoch - 15ms/step
Epoch 1101/2000
1/1 - 0s - loss: 0.4880 - val_loss: 0.4744 - 15ms/epoch - 15

Epoch 1188/2000
1/1 - 0s - loss: 0.4876 - val_loss: 0.4730 - 17ms/epoch - 17ms/step
Epoch 1189/2000
1/1 - 0s - loss: 0.4876 - val_loss: 0.4730 - 15ms/epoch - 15ms/step
Epoch 1190/2000
1/1 - 0s - loss: 0.4876 - val_loss: 0.4730 - 16ms/epoch - 16ms/step
Epoch 1191/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4731 - 16ms/epoch - 16ms/step
Epoch 1192/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4731 - 16ms/epoch - 16ms/step
Epoch 1193/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4730 - 15ms/epoch - 15ms/step
Epoch 1194/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4730 - 16ms/epoch - 16ms/step
Epoch 1195/2000
1/1 - 0s - loss: 0.4877 - val_loss: 0.4730 - 15ms/epoch - 15ms/step
Epoch 1196/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4730 - 15ms/epoch - 15ms/step
Epoch 1197/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4730 - 15ms/epoch - 15ms/step
Epoch 1198/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4729 - 17ms/epoch - 17ms/step
Epoch 1199/2000
1/1 - 0s - loss: 0.4875 - val_loss: 0.4729 - 16ms/epoch - 16

Epoch 1286/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4718 - 15ms/epoch - 15ms/step
Epoch 1287/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4718 - 15ms/epoch - 15ms/step
Epoch 1288/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4718 - 15ms/epoch - 15ms/step
Epoch 1289/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4718 - 14ms/epoch - 14ms/step
Epoch 1290/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4718 - 15ms/epoch - 15ms/step
Epoch 1291/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4718 - 15ms/epoch - 15ms/step
Epoch 1292/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4717 - 16ms/epoch - 16ms/step
Epoch 1293/2000
1/1 - 0s - loss: 0.4874 - val_loss: 0.4717 - 16ms/epoch - 16ms/step
Epoch 1294/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4717 - 15ms/epoch - 15ms/step
Epoch 1295/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4717 - 14ms/epoch - 14ms/step
Epoch 1296/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4717 - 16ms/epoch - 16ms/step
Epoch 1297/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4717 - 17ms/epoch - 17

Epoch 1384/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4708 - 16ms/epoch - 16ms/step
Epoch 1385/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4707 - 15ms/epoch - 15ms/step
Epoch 1386/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4707 - 17ms/epoch - 17ms/step
Epoch 1387/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4707 - 15ms/epoch - 15ms/step
Epoch 1388/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4707 - 16ms/epoch - 16ms/step
Epoch 1389/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4707 - 17ms/epoch - 17ms/step
Epoch 1390/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4706 - 15ms/epoch - 15ms/step
Epoch 1391/2000
1/1 - 0s - loss: 0.4874 - val_loss: 0.4707 - 16ms/epoch - 16ms/step
Epoch 1392/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4707 - 16ms/epoch - 16ms/step
Epoch 1393/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4707 - 15ms/epoch - 15ms/step
Epoch 1394/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4707 - 15ms/epoch - 15ms/step
Epoch 1395/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4706 - 15ms/epoch - 15

Epoch 1482/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4699 - 15ms/epoch - 15ms/step
Epoch 1483/2000
1/1 - 0s - loss: 0.4874 - val_loss: 0.4699 - 16ms/epoch - 16ms/step
Epoch 1484/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4698 - 16ms/epoch - 16ms/step
Epoch 1485/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4698 - 15ms/epoch - 15ms/step
Epoch 1486/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4698 - 18ms/epoch - 18ms/step
Epoch 1487/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4699 - 16ms/epoch - 16ms/step
Epoch 1488/2000
1/1 - 0s - loss: 0.4874 - val_loss: 0.4698 - 16ms/epoch - 16ms/step
Epoch 1489/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4698 - 16ms/epoch - 16ms/step
Epoch 1490/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4698 - 16ms/epoch - 16ms/step
Epoch 1491/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4698 - 15ms/epoch - 15ms/step
Epoch 1492/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4698 - 16ms/epoch - 16ms/step
Epoch 1493/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4698 - 17ms/epoch - 17

Epoch 1580/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4691 - 15ms/epoch - 15ms/step
Epoch 1581/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4691 - 16ms/epoch - 16ms/step
Epoch 1582/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4691 - 16ms/epoch - 16ms/step
Epoch 1583/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4691 - 17ms/epoch - 17ms/step
Epoch 1584/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4691 - 16ms/epoch - 16ms/step
Epoch 1585/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4691 - 17ms/epoch - 17ms/step
Epoch 1586/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4691 - 16ms/epoch - 16ms/step
Epoch 1587/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4691 - 15ms/epoch - 15ms/step
Epoch 1588/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4691 - 16ms/epoch - 16ms/step
Epoch 1589/2000
1/1 - 0s - loss: 0.4874 - val_loss: 0.4691 - 16ms/epoch - 16ms/step
Epoch 1590/2000
1/1 - 0s - loss: 0.4874 - val_loss: 0.4691 - 16ms/epoch - 16ms/step
Epoch 1591/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4691 - 16ms/epoch - 16

Epoch 1678/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4685 - 16ms/epoch - 16ms/step
Epoch 1679/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4685 - 16ms/epoch - 16ms/step
Epoch 1680/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4685 - 16ms/epoch - 16ms/step
Epoch 1681/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4685 - 16ms/epoch - 16ms/step
Epoch 1682/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4684 - 16ms/epoch - 16ms/step
Epoch 1683/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4684 - 16ms/epoch - 16ms/step
Epoch 1684/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4684 - 15ms/epoch - 15ms/step
Epoch 1685/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4684 - 15ms/epoch - 15ms/step
Epoch 1686/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4684 - 16ms/epoch - 16ms/step
Epoch 1687/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4684 - 15ms/epoch - 15ms/step
Epoch 1688/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4684 - 16ms/epoch - 16ms/step
Epoch 1689/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4684 - 17ms/epoch - 17

Epoch 1776/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4679 - 15ms/epoch - 15ms/step
Epoch 1777/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4679 - 16ms/epoch - 16ms/step
Epoch 1778/2000
1/1 - 0s - loss: 0.4869 - val_loss: 0.4679 - 16ms/epoch - 16ms/step
Epoch 1779/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4679 - 16ms/epoch - 16ms/step
Epoch 1780/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4679 - 15ms/epoch - 15ms/step
Epoch 1781/2000
1/1 - 0s - loss: 0.4869 - val_loss: 0.4679 - 15ms/epoch - 15ms/step
Epoch 1782/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4679 - 16ms/epoch - 16ms/step
Epoch 1783/2000
1/1 - 0s - loss: 0.4869 - val_loss: 0.4679 - 15ms/epoch - 15ms/step
Epoch 1784/2000
1/1 - 0s - loss: 0.4869 - val_loss: 0.4679 - 16ms/epoch - 16ms/step
Epoch 1785/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4679 - 16ms/epoch - 16ms/step
Epoch 1786/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4679 - 16ms/epoch - 16ms/step
Epoch 1787/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4679 - 15ms/epoch - 15

Epoch 1874/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 16ms/epoch - 16ms/step
Epoch 1875/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 16ms/epoch - 16ms/step
Epoch 1876/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1877/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1878/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1879/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1880/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1881/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1882/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1883/2000
1/1 - 0s - loss: 0.4869 - val_loss: 0.4674 - 15ms/epoch - 15ms/step
Epoch 1884/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4674 - 16ms/epoch - 16ms/step
Epoch 1885/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4673 - 16ms/epoch - 16

Epoch 1972/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4670 - 16ms/epoch - 16ms/step
Epoch 1973/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4669 - 17ms/epoch - 17ms/step
Epoch 1974/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4669 - 16ms/epoch - 16ms/step
Epoch 1975/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4669 - 16ms/epoch - 16ms/step
Epoch 1976/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4669 - 16ms/epoch - 16ms/step
Epoch 1977/2000
1/1 - 0s - loss: 0.4870 - val_loss: 0.4670 - 15ms/epoch - 15ms/step
Epoch 1978/2000
1/1 - 0s - loss: 0.4871 - val_loss: 0.4670 - 16ms/epoch - 16ms/step
Epoch 1979/2000
1/1 - 0s - loss: 0.4873 - val_loss: 0.4670 - 16ms/epoch - 16ms/step
Epoch 1980/2000
1/1 - 0s - loss: 0.4872 - val_loss: 0.4669 - 16ms/epoch - 16ms/step
Epoch 1981/2000
1/1 - 0s - loss: 0.4868 - val_loss: 0.4669 - 17ms/epoch - 17ms/step
Epoch 1982/2000
1/1 - 0s - loss: 0.4874 - val_loss: 0.4669 - 15ms/epoch - 15ms/step
Epoch 1983/2000
1/1 - 0s - loss: 0.4876 - val_loss: 0.4669 - 16ms/epoch - 16

Memprediksi jumlah kendaraan bermotor di Indonesia pada tahun 2022, dengan memasukkan data total jumlah penduduk di Indonesia dan laju pertumbuhan penduduk pada tahun 2022.

In [16]:
prediksi_2022=model.predict(sc.transform([[275773800, 1.17]]))
print(prediksi_2022)
prediksi_2022=sc_y.inverse_transform(prediksi_2022)
print(f"Prediksi jumlah kendaraan bermotor di Indonesia pada tahun 2022 adalah : {int(prediksi_2022)}")

1/1 [==============================] - 0s 48ms/step
[[0.9999987]]
Prediksi jumlah kendaraan bermotor di Indonesia pada tahun 2022 adalah : 134812736
